# ==== base image ====

FROM alpine:edge

LABEL maintainer="Bruno 'Hyweene' Giarrizzo <bruno@giarrizzo.fr>"

ARG HOME="/home/user"
ENV HOME="${HOME}"

ARG TIMEZONE="Europe/Paris"
ENV TIMEZONE="${TIMEZONE}"

# create a user
RUN set -eux ; \
    adduser -D -h "$HOME" user ; \
    mkdir -p "$HOME/.weechat" ; \
    mkdir -p "$HOME/.config/weechat" ; \
    mkdir -p "$HOME/.local/share/weechat" ; \
    mkdir -p "$HOME/.cache/weechat" ; \
    chown -R user:user "$HOME"

RUN apk add --no-cache tzdata weechat weechat-python weechat-perl weechat-lua

RUN cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && echo "${TIMEZONE}" > /etc/timezone

WORKDIR $HOME

VOLUME "$HOME/.config/weechat"
VOLUME "$HOME/.local/share/weechat"
VOLUME "$HOME/.cache/weechat"

USER user

CMD ["weechat", "--version"]